### ISSUE TITLE
Maximum numbers of queued items?

### ISSUE THREAD

**Issue by gador** [nix-community/queued-build-hook#121]
Hi,

I experience a weird issue with queued-build-hook. When I have a lot of rebuilds and a lot of calls to queued-build-hook's `postBuildScriptContent`. 
Background: I have a limited residential upload speed and a call to upload my build artifacts to my remote server after build. 

When they accumulate and my upload speed is saturated the build pauses, seemingly until it can execute another post-build-hook. 

Is there a limit on the daemon side to cause the post-build-hook to wait? 

My config:
```
      queued-build-hook = {
        enable = true;
        postBuildScriptContent = ''
          set -euo pipefail
          echo "Login to remote-server.com"
          ${pkgs.attic}/bin/attic login gador https://cache.remote-server.com $ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64
          echo "Uploading paths to gador" $OUT_PATHS
          exec ${pkgs.attic}/bin/attic push gador:remote $OUT_PATHS
        '';
        credentials = {
          attic-push = config.age.secrets.attic-push.path;
        };
        concurrency = 1; # > 1 will try to reupload the same drv in parallel
      };
```

**Comment by Mic92** [comment]
Could it be 256? https://github.com/nix-community/queued-build-hook/blob/4bc9c59f89ddf708f6ca603b6091f012451859d6/daemon.go#L46C2-L46C16

**Comment by gador** [comment]
It's really hard to count. AFAIK there is no way to display the number of currently queried jobs.

Maybe I just overlay a patch with a higher number and see whether it helps..

**Comment by Mic92** [comment]
My expectation would have been that if the queue is full it just blocks the processes that try to queue.

**Comment by gador** [comment]
> My expectation would have been that if the queue is full it just blocks the processes that try to queue.

Yes, it seems it does and therefore caused the blocking of building the next derivation after the queue was full. My problem was partly solved (or rather prolonged) by changing the value to something higher. My real problem was a failure of large packages which took about 1h, then failed and then retried (another five times) and blocked the whole queue after a while. 
I solved that problem by just not uploading packages like `steam-run`or `google-fonts` 👍
