### ISSUE TITLE
how to configure the post-build-hook ?

### ISSUE THREAD

**Issue by teto** [nix-community/queued-build-hook#3]
hi, I am interested in using this.

How can I use it ? should my post-build-hook just echo the store path to the socket ? would be nice to add to the README.
Also I wonder who else is using it considering there is 0 ticket. Can i use it in prod or it's more of a toy program. I've seen https://github.com/input-output-hk/spongix but it looks much more complex so I would rather stick to this repo. 

cheers

**Comment by teto** [comment]
so I've built the project so apparently, I need to start a daemon:
`result/bin/queued-build-hook daemon -hook test.sh /tmp/toto`
(it fails on my system: 
```
panic: Systemd pid mismatch

goroutine 1 [running]:
main.RunDaemon(0xc000012140, 0x7fffae1b4163, 0x7, 0xc00001a400)
	/build/go/src/github.com/nix-community/queued-build-hook/daemon.go:27 +0xc25
main.main()
	/build/go/src/github.com/nix-community/queued-build-hook/main.go:59 +0x4d6
```)
and then I can queue packets with `result/bin/queued-build-hook queue -socket /tmp/toto / /nix/store/fig9s0lhik64h2lrfqjb3p4dnnqzq956-neovim-master` ? what is the "wait" command ?

**Comment by Mic92** [comment]
Now there is a nixos module and a test that should help with that: https://github.com/nix-community/queued-build-hook/blob/master/test.nix
